apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentik-os.fullname" . }}-runtime
  labels:
    {{- include "agentik-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
spec:
  type: {{ .Values.runtime.service.type }}
  ports:
    - port: {{ .Values.runtime.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agentik-os.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentik-os.fullname" . }}-dashboard
  labels:
    {{- include "agentik-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
spec:
  type: {{ .Values.dashboard.service.type }}
  ports:
    - port: {{ .Values.dashboard.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agentik-os.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentik-os.fullname" . }}-cli-gateway
  labels:
    {{- include "agentik-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: cli-gateway
spec:
  type: {{ .Values.cliGateway.service.type }}
  ports:
    - port: {{ .Values.cliGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agentik-os.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cli-gateway
